### ISSUE TITLE
Error when set ENV.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [Robinyo/big-top#1]
Hello i come from this issue https://github.com/gshigeto/ionic-environment-variables/issues/15

I change some thing in `webpack.config.ts` 
```
const env = (typeof process.env.MY_ENV == 'undefined') ? process.env.IONIC_ENV : process.env.MY_ENV;
```
I have `test` ENV and you can't set `--prod` with `--livereload` right.

When I set `MY_ENV=prod` it will got an error.
```
MY_ENV=prod ionic cordova emulate ios -lcs --target=iPhone-6
```
But with `ionic cordova emulate ios --prod --target=iPhone-6`  was fine.

![simulator screen shot - iphone 6 - 2017-11-29 at 18 08 23](https://user-images.githubusercontent.com/6513358/33372361-533e995e-d530-11e7-9bcc-29fe012a8be5.png)

**Comment by Robinyo** [comment]
-> Module not found: Error: Can't resolve '@env'

This error means that the TypeScript transpiler cannot resolve the alias -> '@env'

Check your `tsconfig.json`:

```
  "paths": {
    "@env": [ "environments/environment" ],
    ...
  }
```

And your `webpack.config.js`:

```
useDefaultConfig[env].resolve.alias = {
  "@env": path.resolve(environmentPath()),
  ...
};

...

function environmentPath() {

  let filePath = './src/environments/environment' + (env === 'prod' ? '' : '.' + env) + '.ts';

  if (!fs.existsSync(filePath)) {
    console.log(chalk.red('\n' + filePath + ' does not exist!'));
  } else {
    return filePath;
  }
}

```

**Comment by ThunderBirdsX3** [comment]
Not thing change from your example.

**Comment by Robinyo** [comment]
If you clone the Big Top project does it work?

**Comment by ThunderBirdsX3** [comment]
From Big Top project was fine, After change `const env = (typeof process.env.MY_ENV == 'undefined') ? process.env.IONIC_ENV : process.env.MY_ENV;`. It fine except `MY_ENV=prod ionic cordova emulate ios -lcs --target=iPhone-6`. It got an error.

![simulator screen shot - iphone 6 - 2017-11-29 at 18 59 07](https://user-images.githubusercontent.com/6513358/33374296-1ea9929a-d538-11e7-8b15-134229c4a8f6.png)

**Comment by ThunderBirdsX3** [comment]
Only `MY_ENV=prod` will get an error. May be this problem about `@angular/core`.

**Comment by Robinyo** [comment]
See: 
- https://github.com/ionic-team/ionic-app-scripts/issues/1271
- https://github.com/ionic-team/ionic-app-scripts/blob/master/config/webpack.config.js

**Comment by Robinyo** [comment]
-> But with ionic cordova emulate ios --prod --target=iPhone-6 was fine.

See: https://github.com/gshigeto/ionic-environment-variables#if-more-than-prod-and-dev-environments-are-wanted

NOTE: When running with a custom variable, production builds still need --prod flag

-> Why 'MY_ENV=prod' ?

You already have 'dev' and 'prod' via 'process.env.IONIC_ENV'.
