### ISSUE TITLE
ionic serve error 

### ISSUE THREAD

**Issue by abora97** [Robinyo/big-top#4]
when write ionic serve 
this is my output 

> ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
[app-scripts] 'ionic-app-scripts' is not recognized as an internal or external command,
[app-scripts] operable program or batch file.

[INFO] Looks like @ionic/app-scripts isn't installed in this project.

       This package is required for this command to work properly. The package provides a CLI utility, but the
       ionic-app-scripts binary was not found in your PATH.

? Install @ionic/app-scripts? No
[WARN] Not installing--here's how to install manually: npm i -D -E @ionic/app-scripts

[ERROR] @ionic/app-scripts is required for this command to work properly.

**Comment by Robinyo** [comment]
Big Top requires Ionic 3, so try:

```
# Install Ionic 3.9.2 globally using npm
npm install -g ionic@3.9.2

# Clone the project's repo
git clone https://github.com/Robinyo/big-top.git

# Change directory
cd big-top

# Install the project's dependencies
npm install

# Launch the project
npm run ios:dev
```
