### ISSUE TITLE
set icon

### ISSUE THREAD

**Issue by djalili** [Robinyo/big-top#5]
how can i set icon for application ?

**Comment by ahmedragabshaban** [comment]
> how can i set icon for application ?
in resources folder icons icon and inside android/icon

**Comment by Robinyo** [comment]
Do you mean change the [favicon.ico](https://raw.githubusercontent.com/Robinyo/big-top/master/src/assets/icon/favicon.ico)


See: https://github.com/Robinyo/big-top/blob/master/src/index.html#L12
